name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Test
        env:
          CGO_ENABLED: 1
        run: go test -v ./... -race
